### ISSUE TITLE
ssh-base points to centos:6.4 which as of a day or so no longer exists. 

### ISSUE THREAD

**Issue by dbaskette-pivotal** [vmware-archive/dcloud#1]
Should change to centos:6 or centos:latest

**Comment by jaoki** [comment]
@dbaskette-pivotal , thank you for reporting. Indeed the 6.4 tag is gone.
https://registry.hub.docker.com/_/centos/tags/manage/

**Comment by rvs** [comment]
Speaking of which, take a look at this Bigtop JIRA: https://issues.apache.org/jira/browse/BIGTOP-1323 and this Docker repo: https://registry.hub.docker.com/u/bigtop/seed/tags/manage/

What I am saying is that once that JIRA is done (and we're pretty close) you can rely on Apache Bigtop Docker repo for getting official images of OSes that any Hadoop distro is running on. We're also guaranteeing maintenance and lack of disappearing tags ;-)

**Comment by jaoki** [comment]
Hi @rvs I have fixed the issue since it was a blocker with a way @dbaskette-pivotal suggested.
I'm surprised that the tag was just removed from the repo, but we should not rely too much on third party repo either. Lessons learned.

Regarding your comment, we can change FROM image name to "bigtop/seed:centos-6.4" defined in 
https://registry.hub.docker.com/u/bigtop/seed/tags/manage/? , if the image is reliable.
Or the bigtop team is going to have another public docker repo (another URL) that we can use?

**Comment by rvs** [comment]
@jaoki yup you can depend on Bigtop to support the matrix in a reliable way
