### ISSUE TITLE
dcloud doesn't work with Centos epel-repo version of Docker (1.0)

### ISSUE THREAD

**Issue by dbaskette-pivotal** [vmware-archive/dcloud#3]
epel-repo for CentOS has 1.0 vesion of Docker.   There is a bug in it that will not let containers run in privileged mode.   

fix:
To upgrade to a more recent version and fix the bug:
Stop Docker.
wget https://get.docker.io/builds/Linux/x86_64/docker-latest -O $(type -P docker)
Start Docker

**Comment by jaoki** [comment]
hi @dbaskette-pivotal , thank you for sharing your tip!
I am sure some users will fall in to the pitfall and this tip will save them.
That said, we have a small note here https://github.com/gopivotal/dcloud#docker and since it is a user environment configuration, there is nothing we can do on our code base, Thus I'm thinking to close it. 
Please let me know if you have any suggestions we can act upon this issue.

**Comment by dbaskette-pivotal** [comment]
Just close it...   I just wanted to document it somewhere.
